//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by T42.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_T42VIEW                     101
#define IDD_T42_DIALOG                  102
#define IDS_ERR_MALFORMEDREMOTE         102
#define IDP_SOCKETS_INIT_FAILED         103
#define ID_INDICATOR_DATE               104
#define IDS_STATUS_RESOLVING            105
#define IDC_TRAYICON                    105
#define IDS_ERR_REMOTERESOLVEFAILED     106
#define IDD_OPTIONS_SOUNDS              106
#define IDS_ERR_CTLCREATEFAILED         107
#define IDS_ERR_CTLBINDFAILED           108
#define IDS_ERR_CTLGETFAILED            109
#define IDS_ERR_TCPCREATEFAILED         110
#define IDS_ERR_TCPBINDFAILED           111
#define IDS_ERR_TCPGETFAILED            112
#define IDS_STATUS_LOOKUPINVITE         113
#define IDS_ERR_TCPASELFAILED           114
#define IDS_STATUS_WAITINGTOCONNECT     115
#define IDS_ERR_TCPCONNECTFAILED        116
#define IDS_ERR_TCPLISTENFAILED         117
#define IDS_ERR_LTNASELFAILED           118
#define IDS_ERR_CTLLOOKUPFAILED         119
#define IDS_ERR_ANNOUNCEFAILURE         120
#define IDS_CTL_NOTHERE                 121
#define IDS_CTL_FAILED                  122
#define IDS_CTL_MACHUNKNOWN             123
#define IDS_CTL_PERMISSIONDENIED        124
#define IDS_CTL_BADREQUEST              125
#define IDS_CTL_BADVERSION              126
#define IDS_CTL_BADADDR                 127
#define IDR_MAINFRAME                   128
#define IDS_CTL_BADCTL                  128
#define IDR_T42FRAME                    129
#define IDS_CTL_UNKNOWNERROR            130
#define IDI_FULLCUP                     130
#define IDS_ERR_ANNOUNCEFAILED          131
#define IDR_FULLT42                     131
#define IDD_REMOTE                      132
#define IDS_ERR_LEAVINVITEFAILED        132
#define IDS_ERR_TCPACCEPTFAILED         133
#define IDS_STATUS_ANNOUNCING           134
#define IDD_ANNOUNCE                    135
#define IDS_ERR_CTLLDELETEFAILED        135
#define IDS_ERR_CTLRDELETEFAILED        136
#define IDD_OPTIONS_FONTS               136
#define IDS_ERR_TCPERROR                137
#define IDB_BACK                        137
#define IDD_OPTIONS_SECRETARY           137
#define IDS_STATUS_ESTABLISHED          138
#define IDD_OPTIONS_GENERAL             138
#define IDS_STATUS_CONNECTIONCLOSED     139
#define IDM_POPUPS                      139
#define IDW_BEEP_DROP                   140
#define IDS_TITLE_TEAWITH               140
#define IDW_ANNOUNCE_BOILING            141
#define IDS_TITLE_TEAFORTWO             141
#define IDW_WAKE_WHISTLE                142
#define IDS_TITLE_OPTIONS               142
#define IDS_SND_TEADROP                 143
#define IDS_SND_BOILINGTEAPOT           144
#define IDI_BROWSE                      145
#define IDS_SND_TEAPOTWHISTLE           145
#define IDS_TITLE_WAV                   146
#define IDI_T42CALLNEW                  146
#define IDS_FILTER_WAV                  147
#define IDI_T42CALLPROCESSED            147
#define IDS_FMT_T42LOCAL                148
#define IDR_FLIPPEDCUP                  148
#define IDS_FMT_T42REMOTE               149
#define IDS_FMT_T42SYSTEM               150
#define IDI_PREPLAY                     150
#define IDS_CHARSET_AUTO                151
#define IDS_DEFAULTGREETING             152
#define IDS_DEFAULTPARTING              153
#define IDS_FILENAME_T42                153
#define IDS_FORMAT_TIME                 154
#define IDS_RTF_HEAD                    154
#define IDS_FILE_T42CALLS               155
#define IDS_FORMAT_CALLTIME             156
#define IDS_FILTER_RTF                  157
#define IDS_FORMAT_CALLDURATION         158
#define IDS_FORMAT_CALLTIMELONG         159
#define IDS_FORMAT_T42CALLHEADER        160
#define IDS_WSA_ENETDOWN                161
#define IDS_WSA_ECONNRESET              162
#define IDS_WSA_ECONNABORTED            163
#define IDS_WSA_ECONNREFUSED            164
#define IDS_WSA_ENETUNREACH             165
#define IDS_WSA_ETIMEDOUT               166
#define IDS_CONNECTIONCLOSED            167
#define IDS_WSA_NODATA                  168
#define IDS_ERR_CONNECTIONCLOSED        169
#define IDS_WSA_HOSTNOTFOUND            170
#define IDS_KLEVERNET_URL               171
#define IDS_RTF_DELIMITER               172
#define IDS_RTF_TAIL                    173
#define IDS_FAILVALIDATE_NTALKPORT      174
#define IDS_CALLOG_OPEN_FAILED          175
#define IDS_CALLOG_CLOSE_FAILED         176
#define IDS_DAEMON_FAIL                 177
#define IDS_REGISTRYKEY                 178
#define IDS_DEFAULTCALLER               179
#define IDC_CALLEE                      1000
#define IDC_TALK                        1001
#define IDC_OPTIONS                     1002
#define IDC_SPLIT                       1005
#define IDC_CALLER                      1006
#define IDC_TTY                         1008
#define IDC_SECRETARY                   1009
#define IDC_PREVIEW                     1011
#define IDC_CALLS                       1012
#define IDC_ONCALL                      1015
#define IDC_T42BELL_BROWSE              1016
#define IDC_ONCALLAWAY                  1016
#define IDC_T42BELL                     1017
#define IDC_T42PROMPT                   1018
#define IDC_T42PROMPT_BROWSE            1019
#define IDC_T42PROMPT_LOOP              1020
#define IDC_T42WAKE                     1021
#define IDC_T42WAKE_BROWSE              1022
#define IDC_SAMPLE                      1023
#define IDC_T42BELL_PLAY                1023
#define IDC_FORMATNAME                  1024
#define IDC_T42PROMPT_PLAY              1024
#define IDC_FACES                       1025
#define IDC_T42WAKE_PLAY                1025
#define IDC_FONTSIZE                    1026
#define IDC_FORECOLOR                   1027
#define IDC_BACKCOLOR                   1028
#define IDC_BOLD                        1029
#define IDC_ITALIC                      1030
#define IDC_CHARSET                     1031
#define IDC_UNDERLINE                   1032
#define IDC_STRIKEOUT                   1033
#define IDC_TIP                         1034
#define IDC_GREETING                    1035
#define IDC_DOBYTELIMIT                 1038
#define IDC_BYTELIMIT                   1039
#define IDC_DOTIMELIMIT                 1040
#define IDC_TIMELIMIT                   1041
#define IDC_PARTING                     1042
#define IDC_WINLIMIT                    1042
#define IDC_AWAY                        1044
#define IDC_KLEVERNET                   1045
#define IDC_NOTHERE                     1046
#define IDC_REFUSE                      1047
#define IDC_DOWINLIMIT                  1051
#define IDC_TIMESPIN                    1052
#define IDC_WINSPIN                     1053
#define IDC_NTALKPORT                   1053
#define IDC_CHARSPIN                    1054
#define IDC_NTALKPORTSPIN               1054
#define ID_TALK_ABORT                   32771
#define ID_TALK_CLOSE                   32772
#define ID_WINDOW_CENTERSPLITTER        32773
#define ID_WINDOW_SPLITEQUALLY          32774
#define ID_WINDOW_SAVELAYOUT            32775
#define ID_WINDOW_AUTOSAVELAYOUT        32776
#define ID_TALK_REMOTEUSER              32777
#define ID_WINDOW_HORIZONTALSPLIT       32778
#define ID_WINDOW_VERTICALSPLIT         32779
#define ID_TRAY_T42                     32780
#define ID_TRAY_OPTIONS                 32781
#define ID_TRAY_SHOWMAINWINDOW          32782
#define ID_TRAY_EXIT                    32783
#define ID_TALK_RECONNECT               32784
#define ID_WINDOW_HIDEINTRAYONMINIMIZE  32785
#define ID_SLEEP_SLEEP                  32786
#define ID_SLEEP_MAKESOUND              32788
#define ID_SLEEP_POPUP                  32789
#define ID_SLEEP_WAKEUPACTION_MAKESOUND 32790
#define ID_SLEEP_WAKEUPACTION_POPUP     32791
#define ID_SLEEP_SLEEPONMINIMIZE        32792
#define ID_SLEEP_MINIMIZEONSLEEP        32793
#define ID_CALLLOG_CALLBACK             32794
#define ID_CALLLOG_DELETE               32795
#define ID_CALLLOG_SAVETOFILE           32796
#define ID_CALLLOG_EMPTYLOG             32797
#define ID_CALLLOG_MARKASNEW            32798
#define ID_CALLLOG_MARKASPROCESSED      32799
#define ID_TRAY_AWAY                    32800
#define ID_TEA_SAVE                     32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
